stages:
  data_ingestion:
    cmd: python src\pixel_predictor\pipeline\stage_01_data_ingestion.py
    deps:
      - src\pixel_predictor\pipeline\stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.npz



  prepare_base_model:
    cmd: python src\pixel_predictor\pipeline\stage_02_prepare_base_model.py
    deps:
      - src\pixel_predictor\pipeline\stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src\pixel_predictor\pipeline\stage_03_model_training.py
    deps:
      - src\pixel_predictor\pipeline\stage_03_model_training.py
      - config/config.yaml 
      - artifacts/data_ingestion/data.npz
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/training/model.h5





