artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.npz


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  training_data_path: artifacts/data_ingestion/data.npz